name: Testing CI

on: [push]
jobs:
  embold_scan_job:
    runs-on: ubuntu-latest
    name: Embold scan
    steps:
      - uses: actions/checkout@v2
      - name: Embold scan step
        id: embold
        uses: embold/github-action-docker@v0.2
        with:
          embold-url: https://app.embold.io/organization/gh/PeiShan01
          embold-token: ${{ secrets.EMBOLD_TOKEN }}
          repo-config: '/github/workspace/repository-configuration.json'
          repo-uid: 2835c8ac4f279414f4e6e4a9fd232c47
          # Uncomment the below line for verbose logging
          # verbose: true
